// src/components/layout/Header.jsx
import { NavLink } from "react-router";

function Header() {
    const classes = {
        header: "flex flex-col items-center justify-center p-4",
        h1: "font-bold text-3xl underline align-middle text-center",
        h2: "font-bold text-xl align-middle text-center",
    };

    return (
        <header className={classes.header}>
            <div>
                <h1 className={classes.h1}>Hopa</h1>
                <h2 className={classes.h2}>closet virtual</h2>
            </div>

            <div className="flex gap-10 font-bold align-middle justify-center">
                <NavLink to="/">HOME</NavLink>
                <NavLink to="/add-apparel">ADD PECA</NavLink>
                <NavLink to="/outfits">OUTFITS</NavLink>
                <NavLink to="/profile">PERFIL</NavLink>
            </div>
        </header>
    );
}

export default Header;

// frontend/src/lib/components/Header.svelte
<script lang="ts">
  import { page } from '../stores/router'
</script>

<header class="border-b border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
  <div class="container mx-auto px-4 py-4 flex justify-between items-center">
    <a href="/" class="text-2xl font-bold text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
      Hopa
    </a>
    
    <nav class="flex gap-6">
      <a 
        href="/" 
        class="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors {$page === '/' ? 'text-blue-600 dark:text-blue-400' : ''}"
      >
        Closet
      </a>
      <a 
        href="/outfits" 
        class="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors {$page === '/outfits' ? 'text-blue-600 dark:text-blue-400' : ''}"
      >
        Outfits
      </a>
      <a 
        href="/stats" 
        class="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors {$page === '/stats' ? 'text-blue-600 dark:text-blue-400' : ''}"
      >
        Stats
      </a>
    </nav>
  </div>
</header>
